const CUSTOM_COLORMAPS = {
  render3: {
    R: [0, 0, 128, 255, 255],
    G: [255, 0, 128, 0, 252],
    B: [255, 255, 128, 0, 0],
    I: [0, 86, 128, 171, 255],
  },
}

export function registerCustomColormaps(nv) {
  const existingColormaps = new Set(nv.colormaps())

  Object.entries(CUSTOM_COLORMAPS).forEach(([name, colormap]) => {
    if (!existingColormaps.has(name)) {
      nv.addColormap(name, colormap)
    }
  })
}

export const NIIVUE_COLORMAPS = [
  'actc',
  'afni_blues_inv',
  'afni_reds_inv',
  'batlow',
  'bcgwhw',
  'bcgwhw_dark',
  'blue',
  'blue2cyan',
  'blue2magenta',
  'blue2red',
  'bluegrn',
  'bone',
  'bronze',
  'cet_l17',
  'cividis',
  'cool',
  'copper',
  'copper2',
  'ct_airways',
  'ct_artery',
  'ct_bones',
  'ct_brain',
  'ct_brain_gray',
  'ct_cardiac',
  'ct_head',
  'ct_kidneys',
  'ct_liver',
  'ct_muscles',
  'ct_scalp',
  'ct_skull',
  'ct_soft',
  'ct_soft_tissue',
  'ct_surface',
  'ct_vessels',
  'ct_w_contrast',
  'cubehelix',
  'electric_blue',
  'freesurfer',
  'ge_color',
  'gold',
  'gray',
  'green',
  'green2cyan',
  'green2orange',
  'hot',
  'hotiron',
  'hsv',
  'inferno',
  'jet',
  'kry',
  'linspecer',
  'lipari',
  'magma',
  'mako',
  'navia',
  'nih',
  'plasma',
  'random',
  'red',
  'render3',
  'redyell',
  'roi_i256',
  'rocket',
  'surface',
  'thermal',
  'turbo',
  'violet',
  'viridis',
  'warm',
  'winter',
  'x_rain',
]